version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: AWSSDK.Core
    versions:
    - 3.5.2.10
    - 3.5.2.3
    - 3.5.2.6
    - 3.5.2.7
    - 3.5.2.8
    - 3.5.2.9
    - 3.5.3
    - 3.5.3.1
    - 3.5.3.2
    - 3.5.3.3
    - 3.5.3.5
    - 3.5.3.6
    - 3.5.3.7
    - 3.5.3.8
    - 3.7.0
    - 3.7.0.10
    - 3.7.0.11
    - 3.7.0.12
    - 3.7.0.13
    - 3.7.0.14
    - 3.7.0.15
    - 3.7.0.2
    - 3.7.0.3
    - 3.7.0.4
    - 3.7.0.7
    - 3.7.0.8
    - 3.7.0.9
  - dependency-name: AWSSDK.S3
    versions:
    - 3.5.10
    - 3.5.10.1
    - 3.5.7.11
    - 3.5.7.12
    - 3.5.8.1
    - 3.5.8.2
    - 3.5.8.3
    - 3.5.8.4
    - 3.5.8.5
    - 3.5.8.6
    - 3.5.8.7
    - 3.5.8.8
    - 3.5.9
    - 3.5.9.1
    - 3.5.9.3
    - 3.5.9.4
    - 3.5.9.5
    - 3.5.9.6
    - 3.5.9.7
    - 3.5.9.8
    - 3.7.0
    - 3.7.0.10
    - 3.7.0.12
    - 3.7.0.13
    - 3.7.0.14
    - 3.7.0.15
    - 3.7.0.16
    - 3.7.0.2
    - 3.7.0.3
    - 3.7.0.4
    - 3.7.0.7
    - 3.7.0.8
    - 3.7.0.9
